export const PUEBLOS = [
  'Adjuntas',
  'Aguada',
  'Aguadilla',
  'Aguas Buenas',
  'Aibonito',
  'Arecibo',
  'Arroyo',
  'Añasco',
  'Barceloneta',
  'Barranquitas',
  'Bayamón',
  'Cabo Rojo',
  'Caguas',
  'Camuy',
  'Canóvanas',
  'Carolina',
  'Cataño',
  'Cayey',
  'Ceiba',
  'Ciales',
  'Cidra',
  'Coamo',
  'Comerío',
  'Corozal',
  'Culebra',
  'Dorado',
  'Fajardo',
  'Florida',
  'Guayama',
  'Guayanilla',
  'Guaynabo',
  'Gurabo',
  'Guánica',
  'Hatillo',
  'Hormigueros',
  'Humacao',
  'Isabela',
  'Jayuya',
  'Juana Díaz',
  'Juncos',
  'Lajas',
  'Lares',
  'Las Marías',
  'Las Piedras',
  'Loiza',
  'Luquillo',
  'Manatí',
  'Maricao',
  'Maunabo',
  'Mayagüez',
  'Moca',
  'Morovis',
  'Naguabo',
  'Naranjito',
  'Orocovis',
  'Patillas',
  'Peñuelas',
  'Ponce',
  'Quebradillas',
  'Rincón',
  'Rio Grande',
  'Sabana Grande',
  'Salinas',
  'San Germán',
  'San Juan',
  'San Lorenzo',
  'San Sebastián',
  'Santa Isabel',
  'Toa Alta',
  'Toa Baja',
  'Trujillo Alto',
  'Utuado',
  'Vega Alta',
  'Vega Baja',
  'Vieques',
  'Villalba',
  'Yabucoa',
  'Yauco',
] as const;

export const REFERRED_BY = [
  'Un amigo',
  'Otra Compañía',
  'Guagua',
  'Oficina',
  'Radio',
  'Anuncio TV',
  'Flyer',
  'Vecino',
  'Familiar',
  'Otro Cliente',
  'Google / WEB',
  'Social Media',
  'Es Cliente',
  'Fué Cliente',
] as const;

export const ESTATUS = ['Instalada', 'No Instalada', 'En espera'] as const;

export const MOTIVOS = [
  'Quiere es fibra óptica',
  'Quería Internet con TV',
  'Tiene deuda pendiente',
  'Tiene contrato con otra compañía',
  'Se va de viaje',
  'Se va a mudar',
  'Se fue con otra compañía',
  'No tiene el dinero',
  'No puede instalar antena',
  'No LOSS (Residencial Público)',
  'No le da la velocidad que Quiere',
  'No Interesado',
  'No envió documentos',
  'No contesta',
  'Mucha Espera',
  'Es Menor de Edad',
  'Le pareció Caro',
  'Cobertura Negativa',
  'Cliente quedó en llamar',
  'Canceló la visita',
  'Canceló la Solicitud',
  'no indica',
  '',
] as const;

export const PLANES_INSTALADOS = ['25mb', '50Mb', '100Mb', '200Mb'] as const;
